### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by krasnoukhov** [semolex/novaposhta-api-client#5]
Just wanted to bring this discussion up: should this library handle errors that come from the API?

The thing is that API claims to always return 200 so I think there are different errors that need to be handled
- Timeout (when HTTP just does not respond)
- HTTP errors (when API fails to respond, like 500, etc)
- API errors (error returned in JSON response, [codes here](https://developers.novaposhta.ua/listerrorscodes?page=1&quality=50)). Ideally I'd split these up into 2 categories:
  - Auth error
  - Everything else

I think it would be great if this library could handle all of that and provide a common way to deal with it. Currently I'm considering implementing JSON error handling inside of my [integration](https://github.com/krasnoukhov/homeassistant-nova-poshta/blob/c67d51ff0e6608fd62a7128b537f2460ba4255a2/custom_components/nova_poshta/coordinator.py#L39-L45)

**Comment by semolex** [comment]
@krasnoukhov Thanks.
This can be added to roadmap.
Just in case, there is a method in `Common` model which can return error mappings:
```
getMessageCodeText
``` 
I tried to make client as agnostic as possible (e.g. what you send is what you get). 
Currently error handling could be done by wrapping each request with check for `errors` list:
```
{'success': False, 'data': [], 'errors': ['API key incorrect'], 'warnings': [], 'info': [], 'messageCodes': [], 'errorCodes': [], 'warningCodes': [], 'infoCodes': []}
```
Let's keep this thread open so we can discuss how and why we would need to add error handler.
I suggest to make something like `raise_for_errors` flag optional.

UPD: this should also be http-client independent I suppose?

**Comment by krasnoukhov** [comment]
I created a PR that implements these things. I use this approach in [this commit](https://github.com/krasnoukhov/homeassistant-nova-poshta/pull/1/commits/6bd788af62db84ef5f0c9f3f28cdc8278d8173cd) in my integration. Let me know if this works

**Comment by semolex** [comment]
> I created a PR that implements these things. I use this approach in [this commit](https://github.com/krasnoukhov/homeassistant-nova-poshta/pull/1/commits/6bd788af62db84ef5f0c9f3f28cdc8278d8173cd) in my integration. Let me know if this works

Great! Thanks!
